### ISSUE TITLE
Discussion: Update list organization and sections for clarity

### ISSUE THREAD

**Issue by pauly4it** [shuaibiyy/awesome-terraform#176]
## Problem

In the course of the discussion on PR https://github.com/shuaibiyy/awesome-terraform/pull/171, it came up that the current list sections and organizations may no longer be adequate given the size the list has now grown to (a good problem to have!). For example, the Tools section has a mix of open source and free tools as well as SaaS products with and without free tiers.

This can be confusing for an end-user looking for a specific type of tool/product, but it can also be confusing for contributors to the list to determine where a new list addition should be placed.

## Potential Approach

I took a look at the existing list and had a few ideas for how to reorganize the sections, at least as a first pass to set the stage for further organization. Here's how we could organize the list:

- Contents
- Legend
- Official HashiCorp Terraform Resources
- Community
- Resources
	- Books
	- Tutorials and Blog Posts
		- Beginner Guides
		- How-To
		- Cloud Providers
			- Azure
			- AWS
			- Google Cloud
		- Multi-Environment Configuration
		- Security & Compliance
		- Testing & Troubleshooting
		- Writing Custom Providers
		- Miscellaneous
	- Videos
- Providers
	- HashiCorp Supported Providers
	- Vendor Supported Providers
- Community Modules
- Tools & Services
	- General Tools & Services
	- Terraform Enterprise
	- Boilerplates
	- Testing
	- Libraries
	- Private Module Registries
	- Private Provider Registry
	- Editor Plugins
- License

**Comment by pauly4it** [comment]
@chenrui333 Opened this issue to continue our discussion and put up a draft PR as a proposal. I kept the majority of the tools in the "General Tools & Services" section for now, but I recommend breaking that up in follow-up PRs to avoid huge PR changes.

**Comment by pauly4it** [comment]
@chenrui333 just wanted to keep the conversation going. Like I said, this would be the first step to help organize the list, and then it'll (hopefully) be easier to improve organization after that.

**Comment by chenrui333** [comment]
close this for now due to inactivity, feel free to create a new one.
