### ISSUE TITLE
VMWare and Hyper-V providers

### ISSUE THREAD

**Issue by eliassal** [shuaibiyy/awesome-terraform#189]
Hi, are there providers for Vmware and Hyper-V? I came across 1 for Hyper-V , only available option is to compile but without success.
I work in an environment where cloud is not an option we can only work wit our data centes mainly using Hyper-V
Thanks in advance

**Comment by antonbabenko** [comment]
Hi @eliassal !

I'm pretty sure this repository is not the best place to ask such questions because it is about "awesome terraform".

You should have a better reach if you ask such question on more generic forums like https://discuss.hashicorp.com
