### ISSUE TITLE
Discussion: Add a new category called "Provider Development"

### ISSUE THREAD

**Issue by teneko** [shuaibiyy/awesome-terraform#191]
I have just seen, that you support already the category "Writing Custom Providers".

Me as author of [PseudoDynamic.Terraform.Toolset](https://github.com/pseudo-dynamic/PseudoDynamic.Terraform.Toolset) would love to see a category called "Provider Development" where we, the provider library authors, can be represented.

I would like to propose the following change:
...
## Providers
...
## Provider Development
- [terraform-plugin-go](https://github.com/hashicorp/terraform-plugin-go) - A low-level Go binding for the Terraform protocol for integrations to be built on top of. 
- [Terraform Plugin SDK](https://github.com/hashicorp/terraform-plugin-sdk) - Terraform Plugin SDK enables building plugins (providers) to manage any service providers or custom in-house solutions.
- [Terraform Plugin Framework](https://github.com/hashicorp/terraform-plugin-framework) - A next-generation framework for building Terraform providers.
- [PseudoDynamic.Terraform.Plugin.Sdk](https://github.com/pseudo-dynamic/PseudoDynamic.Terraform.Toolset) - Implement Terraform provider plugins, including resources and data sources, in best C# manner.
## Testing
...

May I submit a pull request? 🙂

**Comment by chenrui333** [comment]
Yeah, I think it would be a good idea, I am supporting it. @teneko

**Comment by chenrui333** [comment]
close this for now due to inactivity, feel free to create a new one.
