### ISSUE TITLE
Add JFrog Artifactory Provider

### ISSUE THREAD

**Issue by stefanfreitag** [shuaibiyy/awesome-terraform#214]
[Artifactory](https://jfrog.com/de/artifactory/) is an artifact repository manager developed by JFrog. Over the last three years the companies invest into development of Terraform providers increased. At the moment they offer  three providers
* [artifactory](https://registry.terraform.io/providers/jfrog/artifactory/latest)
* [x-ray](https://registry.terraform.io/providers/jfrog/xray/latest) and
* [project](https://registry.terraform.io/providers/jfrog/project/latest)

From my perspective, I see the [artifactory](https://registry.terraform.io/providers/jfrog/artifactory/latest) provider on awesome-terraform list. This provider allows to manage complete Artifactory installations (repository configuration, user management, etc).

If you are fine, I could provide a pull request.

**Comment by chenrui333** [comment]
yeah, feel free to drop a PR. 💯

**Comment by stefanfreitag** [comment]
Closed by merging pull request #219.
