### ISSUE TITLE
Add these tools

### ISSUE THREAD

**Issue by chaoscreater** [shuaibiyy/awesome-terraform#221]
Here are 2 more tools you can add to the list:
https://github.com/shihanng/tfvar
https://github.com/flavius-dinu/tfgpt

**Comment by antonbabenko** [comment]
Please make a pull-request with the proposed tools.

**Comment by chaoscreater** [comment]
Not sure why that is required?

1. I'm not actively contributing or working on this project

2. It's not even code that we're modifying here. It's literally just links to 2 Github projects and you could have added that to your code directly. Seems like a lot of unnecessary wasted effort to fork/clone and for me to edit and then create a PR for you to merge. I'm just suggesting that you can add those tools to the list, that's all.
